/* Turns exported quiz results (results/*.json from the dashboard) into
   results/leaderboard.md. Zero dependencies — runs on any modern Node.
   Usage: node scripts/leaderboard.mjs [results/foo.json]                    */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'results';
const QUESTIONS = JSON.parse(readFileSync('api/questions.json', 'utf8'));

const files = process.argv[2]
  ? [process.argv[2]]
  : readdirSync(DIR).filter(f => f.endsWith('.json')).sort().map(f => join(DIR, f));

if (!files.length) {
  console.log('No exported results in results/ yet — nothing to do.');
  process.exit(0);
}

const medal = n => ['🥇', '🥈', '🥉'][n] ?? `${n + 1}`;
const out = [
  '# 🏆 Quiz leaderboard', '',
  'Generated by [quiz-results.yml](../.github/workflows/quiz-results.yml) from the results',
  `exported out of the live dashboard. ${QUESTIONS.length} questions · 10 base + difficulty bonus + speed bonus.`, '',
];

for (const file of files) {
  const st = JSON.parse(readFileSync(file, 'utf8'));
  if (!st.board?.length) { console.log(`${file}: no players, skipped`); continue; }
  console.log(`${file}: ${st.board.length} players`);

  out.push(`## ${st.session?.label ?? file} — ${new Date(+st.session?.started_at || Date.now()).toISOString().slice(0, 10)}`, '',
    '| # | Player | Score | Correct | Avg time |', '|---|---|---|---|---|',
    ...st.board.map((r, n) => `| ${medal(n)} | ${r.name} | **${r.score}** | ${r.correct}/${st.total ?? QUESTIONS.length} | ${(r.avg_ms / 1000).toFixed(1)}s |`), '');

  const perQ = (st.perQ ?? []).filter(r => +r.n > 0);
  if (perQ.length) {
    const hardest = [...perQ].sort((a, b) => a.ok / a.n - b.ok / b.n)[0];
    out.push(`<details><summary>Question breakdown — hardest was Q${hardest.qid} (${Math.round(hardest.ok / hardest.n * 100)}% got it)</summary>`, '',
      '| Q | Difficulty | Question | Correct |', '|---|---|---|---|',
      ...perQ.map(r => {
        const q = QUESTIONS.find(x => x.id === +r.qid);
        return `| ${r.qid} | ${q?.d ?? '?'} | ${q?.q ?? ''} | ${Math.round(r.ok / r.n * 100)}% (${r.ok}/${r.n}) |`;
      }), '', '</details>', '');
  }
}

writeFileSync(join(DIR, 'leaderboard.md'), out.join('\n'));
console.log('Wrote results/leaderboard.md');
if (process.env.GITHUB_STEP_SUMMARY)
  writeFileSync(process.env.GITHUB_STEP_SUMMARY, out.join('\n'), { flag: 'a' });
